services:
  - type: web
    name: diabetes-flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11git add render.yaml 
